### ISSUE TITLE
Dynamic value to the decorator like `EntityPartitionKey` | `EntityRowKey`?

### ISSUE THREAD

**Issue by sheikalthaf** [nestjs/azure-database#31]
## I'm submitting a...
It is possible to pass the dynamic value to the decorator like`EntityPartitionKey` | `EntityRowKey`?

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

`@EntityPartitionKey('CatID')` is accepting the string but my paritionKey will be dynamic. It is based on the Entity value.

## Expected behavior

Something i want is like
`@EntityPartitionKey(data => data.Id + data.Name)`

## Environment

<pre><code>
Nest version: 6.9.0

 
For Tooling issues:
- Node version:   v10.17.0
- Platform:   Linux

Others:

</code></pre>

**Comment by EdvardasDlugauskas** [comment]
Was eager to use this change, but it looks like the npm package was last updated 5 months ago. @manekinekko could you create a new release?

**Comment by FedeMDO** [comment]
Yes, fixed on PR [#32](https://github.com/nestjs/azure-database/pull/32) . Apparently the [npm package](https://www.npmjs.com/package/@nestjs/azure-database) isn't updated yet. @manekinekko

**Comment by dinbtechit** [comment]
Ran into the same problem? How I make the `CatID` & `CatName` dynamic for the below example?

``` typescript
import {
  EntityPartitionKey,
  EntityRowKey,
  EntityString,
  EntityIn32
} from '@nestjs/azure-database';

@EntityPartitionKey('CatID')
@EntityRowKey('CatName')
export class Cat {
  @EntityString() name: string;
  @EntityIn32() age: number;
}
```

**Comment by gorootde** [comment]
The contribution in PR #32 seems to be unusable for the purpose described here. The function passed to `@EntityPartitionKey` is evaluated when the entity class is loaded, and not when an object is created.

Thus the `target` the function receives, is always empty and doesn't enable access to the data stored in the entity.
The [test case](https://github.com/sheikalthaf/azure-database/blob/d49ac5dbee4b831de4129e261a32b1a3fcacf6d8/lib/table-storage/azure-table.decorators.spec.ts#L57) written for the contribution only works because default values are loaded even before the decorators.

@manekinekko 
Can we please reopen this issue?
